# Generated by Django 4.1.1 on 2023-03-27 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('board_owner', models.CharField(max_length=256)),
                ('board_name', models.CharField(max_length=150)),
                ('board_description', models.TextField(blank=True, default=None, null=True)),
                ('board_file', models.FileField(blank=True, default=None, null=True, upload_to='task_file_folder')),
                ('board_image', models.ImageField(blank=True, default=None, null=True, upload_to='task_image_folder')),
                ('board_completed', models.BooleanField(blank=True, default=False, null=True)),
                ('board_inprogress', models.BooleanField(blank=True, default=False, null=True)),
                ('board_color', models.CharField(blank=True, max_length=15, null=True)),
                ('board_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('board_date', models.DateTimeField(auto_now_add=True)),
                ('board_dateUpdated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(default=None, max_length=256)),
                ('business_country', models.CharField(default=None, max_length=100)),
                ('business_basicdetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middle_name', models.CharField(blank=True, default='middlename', max_length=100, null=True)),
                ('country', models.CharField(default=None, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_name', models.CharField(blank=True, max_length=150, null=True)),
                ('task_description', models.TextField(blank=True, null=True)),
                ('task_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('task_done', models.BooleanField(default=False)),
                ('task_date', models.DateField(auto_now_add=True, null=True)),
                ('task_dateUpdated', models.DateTimeField(auto_now=True)),
                ('task_assign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.profile')),
                ('task_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.board')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_name', models.CharField(max_length=256)),
                ('project_owner', models.CharField(max_length=256)),
                ('project_description', models.TextField(blank=True, default=None, null=True)),
                ('project_file', models.FileField(blank=True, default=None, null=True, upload_to='task_file_folder')),
                ('project_image', models.ImageField(blank=True, default=None, null=True, upload_to='task_image_folder')),
                ('project_completed', models.BooleanField(blank=True, default=False, null=True)),
                ('project_inprogress', models.BooleanField(blank=True, default=False, null=True)),
                ('project_color', models.CharField(blank=True, max_length=15, null=True)),
                ('project_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('project_date', models.DateTimeField(auto_now_add=True)),
                ('project_dateUpdated', models.DateTimeField(auto_now=True)),
                ('businessProjectowner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.businessprofile')),
                ('personalProjectowner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.profile')),
            ],
        ),
        migrations.AddField(
            model_name='board',
            name='board_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.project'),
        ),
        migrations.AddField(
            model_name='board',
            name='businessBoardowner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.businessprofile'),
        ),
        migrations.AddField(
            model_name='board',
            name='personalBoardowner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.profile'),
        ),
    ]
