# Generated by Django 4.1.1 on 2023-03-28 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='business_name',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
    ]
