# Generated by Django 4.1.1 on 2023-03-28 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_businessprofile_business_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='business_country',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
