# Generated by Django 4.1.1 on 2023-04-18 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_profile_middle_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=256)),
                ('team_description', models.CharField(max_length=256)),
                ('team_purpose', models.CharField(max_length=256)),
                ('team_created', models.DateTimeField(auto_now_add=True)),
                ('team_modified', models.DateTimeField(auto_now=True)),
                ('team_business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.businessprofile')),
            ],
            options={
                'ordering': ['team_business'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('time_joined', models.TimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.profile')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.businessprofile')),
            ],
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='business_member',
            field=models.ManyToManyField(through='backend.Membership', to='backend.profile'),
        ),
    ]
