# Generated by Django 4.1.1 on 2023-04-21 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
