# Generated by Django 4.1.1 on 2023-04-21 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_delete_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256)),
                ('laat_name', models.CharField(max_length=256)),
                ('gender', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=256)),
                ('password', models.CharField(max_length=256)),
            ],
        ),
    ]
