# Generated by Django 4.1.1 on 2023-04-21 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='laat_name',
            new_name='last_name',
        ),
    ]
