# Generated by Django 4.1.1 on 2023-11-10 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_rename_laat_name_test_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_assign',
        ),
    ]
