# Generated by Django 4.1.1 on 2023-11-11 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_remove_task_task_assign'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
