# Generated by Django 4.1.1 on 2023-11-22 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_card_alter_task_task_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='task_date',
            new_name='card_date',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='task_dateUpdated',
            new_name='card_dateUpdated',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='task_done',
            new_name='card_done',
        ),
    ]
