# Generated by Django 4.1.1 on 2023-12-04 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_alter_board_board_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='board_owner',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
